sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - pypy3
  - "nightly"

install:
 - pip install -U pip
 - pip install -U wheel setuptools pbr
 - pip install -U .[docs,test]
 - ls /home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/fixtures-3.0.*.egg-info/
 - cat /home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/fixtures-3.0.*.egg-info/requires.txt
 - pip list
 - python --version

script:
 - make check
 - rst2html.py README README.html
